const assert = require('node:assert/strict');
async function runProjectsSmoke({ win, projects, research, waitFor }) {
  const run = code => win.webContents.executeJavaScript(code), original = projects.get('sc-snr').store.get().papers;
  await run(`document.querySelector('.nav-item[title="项目总览"]').click()`);
  await waitFor(`document.querySelectorAll('.workflow-card').length === 4`);
  const originalFactory = research.readerFactory;
  let call, finish, fail, attempts = 0;
  const ready = async expected => { for (let i = 0; i < 100; i++) { if (attempts === expected) return; await new Promise(resolve => setTimeout(resolve, 20)); } assert.fail('Research backend did not start'); };
  research.readerFactory = () => ({ webResearch: true, close() {}, explain(args) { call = args; attempts++; return new Promise((resolve, reject) => { finish = resolve; fail = reject; args.signal.addEventListener('abort', () => reject(new Error('stopped')), { once: true }); }); } });
  try {
    await run(`document.querySelectorAll('.workflow-card > .button')[1].click()`);
    await waitFor(`Boolean(document.querySelector('.project-run-active'))`);
    await ready(1);
    call.onProgress({ phase: 'waiting', message: '请求已提交，等待 GPT-6 响应…' });
    await waitFor(`document.querySelector('.project-run')?.dataset.phase === 'waiting'`);
    assert.equal(await run(`document.querySelector('.project-run').getBoundingClientRect().top < document.querySelector('.workflow-grid').getBoundingClientRect().top`), true);
    const active = research.jobs.get('sc-snr');
    active.state.startedAt = new Date(Date.now() - 65000).toISOString(); active.state.lastActivityAt = active.state.startedAt;
    await waitFor(`Boolean(document.querySelector('.job-wait-hint')) && document.querySelector('.job-elapsed').textContent.includes('1 分')`);
    call.onProgress({ phase: 'reading', message: '正在核对公开来源…', detail: 'https://example.org/lab' });
    await waitFor(`document.querySelector('.project-run')?.dataset.phase === 'reading' && !document.querySelector('.job-wait-hint')`);
    await run(`document.querySelector('.nav-item[title="PI 与实验室"]').click()`);
    await waitFor(`document.querySelectorAll('.pi-card').length === 12`);
    await run(`document.querySelector('.nav-item[title="项目总览"]').click()`);
    await waitFor(`Boolean(document.querySelector('.project-run-active .project-section-title button'))`);
    await run(`document.querySelector('.project-run-active .project-section-title button').click()`);
    await waitFor(`document.querySelector('.project-run')?.dataset.status === 'interrupted' && !document.querySelectorAll('.workflow-card > .button')[1].disabled`);
    await run(`document.querySelectorAll('.workflow-card > .button')[1].click()`);
    await waitFor(`Boolean(document.querySelector('.project-run-active'))`);
    await ready(2); call.onSearch({ id: 'source1', type: 'webSearch', action: { url: 'https://example.org/lab' } });
    call.onProgress({ phase: 'writing', message: '正在整理结果…' });
    await waitFor(`document.querySelector('.project-run')?.dataset.phase === 'writing'`);
    finish(JSON.stringify({ summary: '调研核验完成。', complete: true, checkedCount: 0, searchedSources: ['测试来源'], candidates: [], profiles: [], events: [] }));
    await waitFor(`document.querySelector('.project-run')?.dataset.status === 'completed' && !document.querySelectorAll('.workflow-card > .button')[1].disabled`);
    assert.equal(await run(`document.querySelector('.project-run').textContent.includes('查看 PI 与实验室')`), true);
    await run(`document.querySelectorAll('.workflow-card > .button')[1].click()`);
    await waitFor(`Boolean(document.querySelector('.project-run-active'))`);
    await ready(3); fail(new Error('连接测试失败'));
    await waitFor(`document.querySelector('.project-run')?.dataset.status === 'failed' && !document.querySelectorAll('.workflow-card > .button')[1].disabled`);
    console.log('RESEARCH_UI_OK: visible progress, elapsed time, delayed response hint, usable PI navigation, stop, restart, completion and failure recovery.');
  } finally { await research.close(); research.readerFactory = originalFactory; }
  await run(`document.querySelector('.nav-item[title="PI 与实验室"]').click()`);
  await waitFor(`document.querySelectorAll('.pi-card').length === 12`);
  await run(`document.querySelector('.pi-card-top > button').click()`);
  await waitFor(`document.querySelector('.pi-card-top > button').textContent.includes('已关注')`);
  const pi = projects.get('sc-snr').store.get().people.profiles[0]; assert.equal(pi.followed, true);
  await require('./pi-dossier-smoke.cjs').runPiDossierSmoke({ win, context: projects.get('sc-snr'), waitFor });
  await run(`document.querySelector('.new-project-button').click()`);
  await waitFor(`Boolean(document.querySelector('.project-dialog[open]'))`);
  await run(`(()=>{const form=document.querySelector('.project-dialog form'); const set=(selector,value)=>{const field=form.querySelector(selector);Object.getOwnPropertyDescriptor(field.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,'value').set.call(field,value);field.dispatchEvent(new Event('input',{bubbles:true}));};set('input[required]','Project isolation fixture');set('textarea[required]','How do hippocampal circuits guide spatial memory?');})()`);
  await run(`document.querySelector('.project-dialog form').requestSubmit()`);
  await waitFor(`Boolean(document.querySelector('.project-heading h1')?.textContent.includes('Project isolation fixture')) && !document.querySelector('.project-switching')`);
  const secondId = projects.index.activeId; assert.notEqual(secondId, 'sc-snr'); assert.equal(projects.get().store.get().papers.length, 0);
  assert.equal(projects.get().store.get().people, undefined);
  await run(`document.querySelector('.nav-item[title="PI 与实验室"]').click()`);
  await waitFor(`Boolean(document.querySelector('.people-page .empty-state'))`);
  assert.equal(await run(`document.querySelectorAll('.pi-card').length`), 0);
  await run(`(()=>{const select=document.querySelector('select[aria-label="切换研究项目"]');select.value='sc-snr';select.dispatchEvent(new Event('change',{bubbles:true}));})()`);
  await waitFor(`Boolean(document.querySelector('.library-title')) && document.querySelector('select[aria-label="切换研究项目"]').value === 'sc-snr'`);
  assert.deepEqual(projects.get().store.get().papers, original);
  assert.equal(projects.get().store.get().people.profiles[0].followed, true);
  console.log('PROJECTS_OK: project creation, empty isolated library, real UI switching, PI follow persistence and original papers unchanged.');
  return { projects: true, people: true, researchProgress: true, piDossiers: true };
}
module.exports = { runProjectsSmoke };
