import React, { useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, ExternalLink, FileText, FlaskConical, Search, Users, RefreshCw, Download, Network, BookOpen } from 'lucide-react';
import { api, downloadText } from './bridge';
import { cnsJournal, eligibleWorks, summarize, keywords, coauthors, classification, confirmed, fundingLabel, norm } from './pi-metrics.mjs';
import './pi-detail.css';
import DOMPurify from 'dompurify';
import { marked } from 'marked';

const rankNames = { cas: '中科院大类一区', jcr: 'JCR Q1' };
function SourceLinks({ sources = [], notify }) { return <div className="dossier-sources">{sources.map((s, i) => <button className="text-button" key={s.url + i} onClick={() => api.openExternal(s.url).catch(e => notify(e.message))}>{s.label}<ExternalLink size={12} /></button>)}</div>; }
function Empty({ children }) { return <p className="dossier-empty">{children}</p>; }
function RichText({ value, notify, inline = false }) { const html = useMemo(() => DOMPurify.sanitize(marked.parse(value || ''), { ALLOWED_TAGS: inline ? ['strong', 'em', 'a'] : ['p', 'br', 'strong', 'em', 'ul', 'ol', 'li', 'a'], ALLOWED_ATTR: ['href'] }), [value, inline]); const Tag = inline ? 'span' : 'div'; return <Tag className="dossier-rich-text" onClick={e => { const a = e.target.closest('a'); if (a) { e.preventDefault(); api.openExternal(a.href).catch(error => notify(error.message)); } }} dangerouslySetInnerHTML={{ __html: html }} />; }

function PublicationChart({ data, selected, select, hasRankings }) {
  const maximum = Math.max(1, ...data.years.map(y => y.total));
  return <div className="publication-chart"><div className="chart-legend"><span><i className="legend-total" />期刊论文（含综述）</span><span><i className="legend-cns" />其中 CNS 本刊</span>{hasRankings && <span><i className="legend-q1" />其中 SCI 一区</span>}</div><div className="year-bars" role="group" aria-label="近十年论文发表图；点击年份筛选论文">{data.years.map(y => <button key={y.year} className={`year-bar ${selected === y.year ? 'selected' : ''}`} aria-pressed={selected === y.year} aria-label={`${y.year} 年 ${y.total} 篇，CNS ${y.cns} 篇`} onClick={() => select(selected === y.year ? null : y.year)}><span className="year-value">{y.total}</span><span className="bar-space"><span className="bar-total" style={{ height: `${y.total / maximum * 100}%` }} /><span className="bar-cns" style={{ height: `${y.cns / maximum * 100}%` }} />{hasRankings && y.q1 > 0 && <span className="bar-q1" style={{ bottom: `${y.q1 / maximum * 100}%` }} title={`SCI 一区 ${y.q1} 篇`} />}</span><span className="bar-year">{y.year}</span></button>)}</div></div>;
}

function RelationshipGraph({ person, relations, collaborators, notify }) {
  const [mode, setMode] = useState('training'), [selected, setSelected] = useState(null);
  const mentors = relations.filter(r => r.type === 'mentor'), trainees = relations.filter(r => r.type === 'trainee');
  const collabs = collaborators.slice(0, 8);
  const height = mode === 'training' ? Math.max(310, Math.max(mentors.length, trainees.length, 1) * 90 + 80) : 560;
  const center = { x: 440, y: height / 2 };
  const nodes = mode === 'training' ? [...mentors.map((r, i) => ({ ...r, key: 'm' + i, x: 125, y: 75 + i * 90, label: r.stage || '导师' })), ...trainees.map((r, i) => ({ ...r, key: 't' + i, x: 755, y: 75 + i * 90, label: r.destination || r.stage || '受指导者' }))] : collabs.map((r, i) => ({ ...r, key: r.key, x: i % 2 ? 755 : 125, y: 80 + Math.floor(i / 2) * 130, label: `${r.papers.length} 篇共同署名`, type: 'coauthor' }));
  return <section className="dossier-section"><div className="dossier-section-heading"><div><h2>学术关系图</h2><p>点选人物，查看关系依据或共同论文。</p></div><div className="graph-switch"><button className={mode === 'training' ? 'active' : ''} onClick={() => { setMode('training'); setSelected(null); }}>师承与学生去向</button><button className={mode === 'collaboration' ? 'active' : ''} onClick={() => { setMode('collaboration'); setSelected(null); }}>论文合作网络</button></div></div>
    {nodes.length ? <div className="relationship-canvas"><svg viewBox={`0 0 880 ${height}`} role="group" aria-label={mode === 'training' ? '有来源的师承关系图' : '依据共同署名生成的合作图'}><defs><marker id="pi-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#86a498" /></marker></defs>{nodes.map(n => { const left = n.x < center.x; return <path key={'edge' + n.key} d={left ? `M ${n.x + 105} ${n.y} C 320 ${n.y}, 285 ${center.y}, ${center.x - 106} ${center.y}` : `M ${center.x + 106} ${center.y} C 595 ${center.y}, 560 ${n.y}, ${n.x - 105} ${n.y}`} fill="none" stroke="#aac0b2" strokeWidth="1.6" markerEnd={mode === 'training' ? 'url(#pi-arrow)' : undefined} />; })}<g className="graph-center" transform={`translate(${center.x},${center.y})`}><rect x="-107" y="-36" width="214" height="72" rx="14" /><text textAnchor="middle" y="-2">{person.name}</text><text textAnchor="middle" y="20" className="graph-subtitle">当前 PI</text></g>{nodes.map(n => <g key={n.key} role="button" tabIndex="0" aria-label={`查看 ${n.name} 的关系依据`} className={`graph-node ${selected?.key === n.key ? 'selected' : ''}`} transform={`translate(${n.x},${n.y})`} onClick={() => setSelected(n)} onKeyDown={e => { if (['Enter', ' '].includes(e.key)) { e.preventDefault(); setSelected(n); } }}><rect x="-104" y="-32" width="208" height="64" rx="11" /><text textAnchor="middle" y="-3">{n.name.length > 27 ? n.name.slice(0, 25) + '…' : n.name}</text><text textAnchor="middle" y="17" className="graph-subtitle">{n.label.length > 24 ? n.label.slice(0, 22) + '…' : n.label}</text></g>)}</svg></div> : <Empty>尚未核实到这类关系。可使用“深入更新档案”继续查找；没有记录不代表没有导师或学生。</Empty>}
    {mode === 'collaboration' && <p className="dossier-note">仅由本页纳入统计的论文共同署名生成，最多展示 8 位。无 ORCID 的姓名尚未消歧；共同署名不能证明师承关系或实质合作程度。</p>}
    {selected && <div className="relation-evidence"><h3>{selected.name}</h3>{selected.type === 'coauthor' ? <><p>{selected.orcid ? `ORCID：${selected.orcid}` : '作者姓名匹配；未确认独立身份。'}</p>{selected.papers.slice(0, 12).map(w => <button className="paper-evidence-link" key={w.id} onClick={() => api.openExternal(w.url).catch(e => notify(e.message))}>{w.publishedDate.slice(0, 4)} · {w.title}<ExternalLink size={12} /></button>)}</> : <><p>{selected.stage} · {selected.period || '时间待核实'}</p><p>{selected.detail}</p><p><b>去向：</b>{selected.destination || '尚未核实'}{selected.destinationAsOf && `（核对：${selected.destinationAsOf}）`}</p><SourceLinks sources={selected.sources} notify={notify} /></>}</div>}
    {mode === 'training' && trainees.length > 0 && <div className="alumni-table"><h3>学生与博士后去向</h3><table><thead><tr><th>姓名 / 阶段</th><th>公开去向</th><th>核对日期与依据</th></tr></thead><tbody>{trainees.map((r, i) => <tr key={i}><td><b>{r.name}</b><small>{r.stage} · {r.period || '时间未披露'}</small></td><td>{r.destination || '尚未核实'}</td><td>{r.destinationAsOf || '待核实'}<SourceLinks sources={r.sources} notify={notify} /></td></tr>)}</tbody></table></div>}
    {relations.filter(r => r.type === 'collaborator').map((r, i) => <div className="relation-evidence" key={i}><h3>公开项目合作 · {r.name}</h3><p>{r.detail}</p><SourceLinks sources={r.sources} notify={notify} /></div>)}
  </section>;
}

export default function PiDetail({ person, people, project, back, update, start, busy, statusPanel, refresh, notify }) {
  const [tab, setTab] = useState(person.dossier ? 'overview' : 'publications'), [year, setYear] = useState(null), [term, setTerm] = useState(''), [uncertain, setUncertain] = useState(false), [position, setPosition] = useState('all'), [kind, setKind] = useState('all');
  const [system, setSystem] = useState('cas'), [rankYear, setRankYear] = useState(''), [listFilter, setListFilter] = useState('all'), [limit, setLimit] = useState(30), [importing, setImporting] = useState(false);
  const dossier = person.dossier, bibliography = person.bibliography, rankings = people.rankings || [];
  const availableYears = [...new Set(rankings.filter(r => r.system === system).map(r => r.year))].sort((a, b) => b - a), selectedRankYear = rankYear || availableYears[0] || '';
  const works = useMemo(() => eligibleWorks(bibliography, { uncertain, position, kind }), [bibliography, uncertain, position, kind]);
  const data = useMemo(() => summarize(works, bibliography, rankings, system, selectedRankYear), [works, bibliography, rankings, system, selectedRankYear]);
  const topics = useMemo(() => keywords(works), [works]), collaborators = useMemo(() => coauthors(works), [works]);
  const pendingCount = (bibliography?.works || []).filter(w => !confirmed(w) && ['article', 'review'].includes(w.kind)).length;
  const filtered = works.filter(w => (!year || Number(w.publishedDate.slice(0, 4)) === year) && (!term || norm(w.title + ' ' + w.keywords.join(' ')).includes(norm(term))) && (listFilter !== 'cns' || cnsJournal(w)) && (listFilter !== 'q1' || classification(w, rankings, system, selectedRankYear).q1));
  const events = people.events.filter(e => e.piId === person.id);
  async function importRanks() { setImporting(true); try { const result = await api.importJournalRankings(); if (result) { await refresh(); notify(`已导入 ${result.imported} 条期刊分区记录。`); } } catch (e) { notify(e.message); } finally { setImporting(false); } }
  const csvTemplate = 'system,year,issn,journal,category,quartile,scie,source\n';
  return <div className="project-scroll"><div className="project-page pi-detail"><button className="text-button back-to-people" onClick={back}><ArrowLeft size={16} />返回 PI 与实验室</button><div className="page-eyebrow">RESEARCHER DOSSIER · {project.name}</div><div className="pi-detail-heading"><div className="pi-large-avatar">{person.name.split(/\s/).slice(0, 2).map(s => s[0]).join('')}</div><div><h1>{person.name}</h1><p>{person.institution}</p><SourceLinks sources={[{ label: '官方主页', url: person.website }]} notify={notify} /></div><button className={`button ${person.followed ? 'pi-followed' : ''}`} onClick={() => update(person.id, { followed: !person.followed }).catch(e => notify(e.message))}>{person.followed ? <Check size={14} /> : <Users size={14} />}{person.followed ? '已关注' : '关注 PI'}</button></div>
    <div className="dossier-actions"><button className="button primary" disabled={busy} onClick={() => start(person.id, 'dossier')}><Search size={15} />深入更新档案</button><button className="button" disabled={busy} onClick={() => start(person.id, 'bibliography')}><RefreshCw size={15} />更新论文数据</button><span>档案核对：{dossier?.checkedOn || '待补全'} · 论文更新：{bibliography?.checkedOn || '待获取'}</span></div>{statusPanel}
    <nav className="dossier-tabs" aria-label="PI 档案栏目">{[['overview', '研究与经历', FlaskConical], ['publications', '论文与关键词', BookOpen], ['network', '学术关系', Network], ['funding', '资助与项目', FileText]].map(([id, label, Icon]) => <button key={id} className={tab === id ? 'active' : ''} aria-current={tab === id ? 'page' : undefined} onClick={() => setTab(id)}><Icon size={16} />{label}</button>)}</nav>
    {tab === 'overview' && <><section className="dossier-section"><h2>研究画像</h2><div className="dossier-overview"><RichText value={dossier?.overview || person.focus} notify={notify} /></div><div className="pi-project-fit"><span>与你的项目有关 · 分析</span><p>{person.relevance}</p></div><SourceLinks sources={dossier?.sources || person.sources} notify={notify} />{dossier?.scope && <p className="dossier-note">本轮覆盖：{dossier.scope}</p>}</section><div className="dossier-two-columns"><section className="dossier-section"><h2>研究方向与方法</h2>{dossier?.directions?.length ? dossier.directions.map((d, i) => <div className="research-direction" key={i}><h3>{d.title}</h3><p>{d.detail}</p><SourceLinks sources={d.sources} notify={notify} /></div>) : <p>{person.focus}</p>}<div className="method-tags">{dossier?.methods.map(m => <RichText inline key={m} value={m} notify={notify} />)}</div></section><section className="dossier-section"><h2>教育与职业经历</h2>{dossier?.career?.length ? <ol className="career-timeline">{dossier.career.map((c, i) => <li key={i}><span>{c.period || '时间待核实'}</span><h3>{c.role}</h3><b>{c.institution}</b><p>{c.detail}</p><SourceLinks sources={c.sources} notify={notify} /></li>)}</ol> : <Empty>博士、博士后及任职经历尚待核实。点击“深入更新档案”获取带来源的履历。</Empty>}</section></div><section className="dossier-section"><h2>继续了解这个实验室</h2><SourceLinks sources={dossier?.resources || [{ label: '访问官方主页', url: person.website }]} notify={notify} />{dossier?.questions?.length > 0 && <ul className="dossier-questions">{dossier.questions.map((q, i) => <li key={i}>{q}</li>)}</ul>}<button className="text-button" onClick={() => setTab('publications')}>查看十年论文与研究主题 <ArrowRight size={14} /></button></section></>}
    {tab === 'publications' && <><section className="dossier-section"><div className="dossier-section-heading"><div><h2>近十年发表状况</h2><p>{bibliography ? `${bibliography.fromYear}–${bibliography.toDate.slice(0, 4)} · 截至 ${bibliography.toDate}（末年尚未结束）` : '获取数据后按最近十个日历年展示'}</p></div><div className="publication-selects"><select aria-label="论文署名位置" value={position} onChange={e => setPosition(e.target.value)}><option value="all">全部署名位置</option><option value="first">第一作者</option><option value="last">末位作者</option></select><select aria-label="统计论文类型" value={kind} onChange={e => setKind(e.target.value)}><option value="all">研究论文与综述</option><option value="article">研究论文</option><option value="review">综述</option></select></div></div>
      <div className="pi-stat-grid"><div><span>纳入统计的期刊论文</span><b>{bibliography ? data.total : '—'}<small>篇</small></b><p>按 DOI 去重，排除预印本与更正等</p></div><button onClick={() => setListFilter(listFilter === 'cns' ? 'all' : 'cns')}><span>CNS 本刊</span><b>{bibliography ? data.cnsTotal : '—'}<small>篇</small></b><p>{bibliography ? `C ${data.cns.Cell} · N ${data.cns.Nature} · S ${data.cns.Science}` : '等待论文数据'}</p></button><button onClick={() => setListFilter(listFilter === 'q1' ? 'all' : 'q1')} disabled={!data.known}><span>{rankNames[system]} · SCI</span><b>{data.q1 ?? '—'}<small>{data.q1 == null ? '待匹配' : '篇'}</small></b><p>{data.known ? `已分类 ${data.known} / ${data.total} 篇；待分类 ${data.unknown} 篇` : '尚无可核对的分区表'}</p></button></div>
      {bibliography ? <><PublicationChart data={data} selected={year} select={setYear} hasRankings={data.known > 0} /><p className="dossier-note">统计为本次检索覆盖范围内的结果，并非完整生涯总产出。CNS 仅含 Cell、Nature、Science 本刊，子刊另计；末位作者不等同于通讯作者。</p><label className="identity-toggle"><input type="checkbox" checked={uncertain} onChange={e => setUncertain(e.target.checked)} />也纳入姓名匹配但单位 / ORCID 尚待确认的条目（{pendingCount} 篇）</label>{uncertain && <p className="dossier-warning">当前图表包含待消歧条目，不能当作已核验的个人完整业绩。</p>}<details className="dossier-coverage"><summary>数据覆盖与作者身份核对</summary><p>默认仅纳入作者全名与单位相符或 ORCID 对应的论文。姓名：{bibliography.identity.names.join(' / ')}。用于核对的单位线索：{bibliography.identity.affiliations.join(' / ')}。</p><p>数据库返回 {bibliography.hitCount} 条，保留 {bibliography.works.length} 条去重记录。另有预印本 {(bibliography.works || []).filter(w => w.kind === 'preprint').length} 条；不会加入上方期刊统计。{bibliography.complete ? '本查询分页已取完；其他数据库或署名别名仍可能遗漏。' : '本查询尚未全部取完，统计不完整。'}</p><SourceLinks sources={[{ label: '查看 Europe PMC 原始检索', url: bibliography.sourceUrl }]} notify={notify} /></details></> : <Empty>点击“更新论文数据”从公开数据库获取记录，无需 API Key。没有获取到的数据不会显示为零。</Empty>}
      <details className="ranking-settings"><summary>SCI 一区的口径与分区表</summary><div className="ranking-controls"><select aria-label="SCI 一区统计口径" value={system} onChange={e => { setSystem(e.target.value); setRankYear(''); }}><option value="cas">中科院 · 大类一区</option><option value="jcr">JCR · Q1</option></select><select aria-label="期刊分区版本年份" value={selectedRankYear} onChange={e => setRankYear(e.target.value)}>{!availableYears.length && <option value="">尚未导入版本</option>}{availableYears.map(y => <option key={y} value={y}>{y} 年版</option>)}</select><button className="button" disabled={importing} onClick={importRanks}><Download size={14} />导入分区表</button><button className="text-button" onClick={() => downloadText('NeuroShelf-期刊分区模板.csv', '\uFEFF' + csvTemplate, 'text/csv;charset=utf-8')}>下载空白模板</button></div><p>将学校取得的分区数据按模板填入后导入。cas 必须填写“大类”分区；jcr 填写相应学科 Q1–Q4。SCIE 收录单独核实，不能用 Q1 代替。支持 CSV 与 NeuroShelf JSON。</p><p>口径：以所选版本对十年论文做统一回溯分类，按 ISSN 匹配；已导入分类中任一 SCI 一区即计入。并非论文发表当年的历史分区。未匹配项保留未知，已知一区数量可能只是下限。</p><SourceLinks sources={[{ label: '中科院分区官方平台', url: 'https://www.fenqubiao.com/' }, { label: 'JCR 官方平台', url: 'https://jcr.clarivate.com/' }]} notify={notify} /></details>
    </section><section className="dossier-section"><h2>十年研究主题</h2><p className="dossier-note">按论文的作者关键词与 MeSH 主题词统计，每篇同一词计一次，已去除常见物种等泛词。点词可筛选论文；主题频率不代表研究质量。</p>{topics.length ? <div className="keyword-cloud">{topics.map(t => <button key={t.term} className={term === t.term ? 'selected' : ''} style={{ fontSize: `${13 + 9 * t.count / topics[0].count}px` }} onClick={() => setTerm(term === t.term ? '' : t.term)}>{t.term}<small>{t.count}</small></button>)}</div> : <Empty>当前条目没有可用主题词，待数据库补全后可更新。</Empty>}</section><section className="dossier-section"><div className="dossier-section-heading"><h2>可追溯的论文清单 · {filtered.length}</h2><button className="text-button" onClick={() => { setYear(null); setTerm(''); setListFilter('all'); }}>清除年份与主题筛选</button></div><div className="dossier-paper-search"><Search size={16} /><input aria-label="搜索 PI 的论文或关键词" placeholder="搜索标题或主题词…" value={term} onChange={e => setTerm(e.target.value)} /><select aria-label="PI 论文列表分类" value={listFilter} onChange={e => setListFilter(e.target.value)}><option value="all">全部期刊</option><option value="cns">仅 CNS 本刊</option><option value="q1">仅已匹配 SCI 一区</option></select></div>{year && <p className="dossier-note">当前年份：{year}</p>}<div className="dossier-paper-list">{filtered.slice(0, limit).map(w => <article key={w.id}><div className="dossier-paper-meta"><span>{w.publishedDate}</span><span>{w.journal}</span>{cnsJournal(w) && <b>CNS 本刊</b>}<span>{w.kind === 'review' ? '综述' : '研究论文'}</span>{!confirmed(w) && <b className="unconfirmed">身份待确认</b>}</div><button className="paper-title-link" onClick={() => api.openExternal(w.url).catch(e => notify(e.message))}>{w.title}<ExternalLink size={13} /></button><p>{w.authors.slice(0, 5).map(a => a.name).join(', ')}{w.authors.length > 5 && ` 等 ${w.authors.length} 位作者`}</p><small>本人署名：{w.piAuthor} · {({ first: '第一作者', last: '末位作者', middle: '中间作者', sole: '独立作者' })[w.authorPosition]} · Europe PMC 被引 {w.citations}{w.doi && ` · DOI ${w.doi}`}</small></article>)}</div>{filtered.length > limit && <button className="button" onClick={() => setLimit(limit + 30)}>再显示 30 篇</button>}{!filtered.length && <Empty>暂无符合当前筛选的记录。</Empty>}</section></>}
    {tab === 'network' && <RelationshipGraph person={person} relations={dossier?.relationships || []} collaborators={collaborators} notify={notify} />}
    {tab === 'funding' && <><section className="dossier-section"><h2>资助与正在做的项目</h2><p className="dossier-note">本人角色、联盟总额与课题组经费分别注明。论文致谢中的资助不直接当作本人当前在研经费；下方状态以来源核对日及公开项目期为依据。</p>{dossier?.funding?.length ? <div className="funding-grid">{dossier.funding.map((g, i) => <article className="funding-card" key={i}><div className="funding-card-top"><span>{g.funder}</span><b>{fundingLabel(g)}</b></div><h3>{g.title}</h3><dl><div><dt>项目编号</dt><dd>{g.grantId || '未披露'}</dd></div><div><dt>本人角色</dt><dd>{g.role || '待核实'}</dd></div><div><dt>经费口径</dt><dd>{g.amount || '未披露'}</dd></div><div><dt>公开项目期</dt><dd>{g.start || '起始待核实'} — {g.end || '结束待核实'}</dd></div></dl><p>{g.detail}</p><p className="dossier-note">{g.caveat}</p><SourceLinks sources={g.sources} notify={notify} /></article>)}</div> : <Empty>当前持有的资助尚待核实。点击“深入更新档案”查找资助方与机构原始记录，未查到不能理解为没有经费。</Empty>}</section>{events.length > 0 && <section className="dossier-section"><h2>已记录的实验室动态</h2>{events.map(e => <article className="dossier-event" key={e.id}><span>{e.eventDate || '事件日期未披露'} · {e.baseline ? '历史背景' : '公开动态'}</span><h3>{e.title}</h3><p>{e.summary}</p><p className="dossier-note">{e.caveat}</p><SourceLinks sources={e.sources} notify={notify} /></article>)}</section>}</>}
  </div></div>;
}
