import { t, tx, te, dateLocale } from './i18n';
import React, { useEffect, useRef, useState } from 'react';
import { ArrowRight, BookOpen, CalendarDays, Check, Download, ExternalLink, FolderOpen, LoaderCircle, Plus, Search, Settings2, Sparkles, Users, X, GitBranch } from 'lucide-react';
import { api } from './bridge';
import { effortLabel } from './ai-options';
import PiDetail from './PiDetail';
import './projects.css';

export function ProjectPicker({ projects, active, onSwitch, onNew }) {
  return <div className="project-picker"><label className="project-selector"><div className="project-initial">P</div><div><span>{t("研究项目")}</span><select aria-label={t("切换研究项目")} value={active?.id || ''} onChange={e => onSwitch(e.target.value)}>{projects.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></div></label><button className="new-project-button" onClick={onNew}><Plus size={14} />{t("新建项目")}</button></div>;
}

export function ProjectDialog({ project, onClose, onSave }) {
  const ref = useRef(null), [form, setForm] = useState({ name: project?.name || '', question: project?.question || '', keywords: project?.keywords?.join(', ') || '', species: project?.species || '', exclusions: project?.exclusions || '', weeklyEnabled: project?.weeklyEnabled ?? true });
  const [busy, setBusy] = useState(false), [error, setError] = useState('');
  useEffect(() => { ref.current.showModal(); return () => ref.current?.close(); }, []);
  const field = (key, label, placeholder, multiline = false) => <label className="project-field">{label}{multiline ? <textarea required={key === 'question'} value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })} placeholder={placeholder} rows={key === 'question' ? 3 : 2} /> : <input required={key === 'name'} value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })} placeholder={placeholder} maxLength={key === 'name' ? 100 : 500} />}</label>;
  return <dialog ref={ref} className="modal project-dialog" onCancel={e => { if (busy) e.preventDefault(); else onClose(); }}><form onSubmit={async e => { e.preventDefault(); setBusy(true); setError(''); try { await onSave(form); } catch (err) { setError(err.message); setBusy(false); } }}><div className="modal-head"><div><h2>{project ? t("项目设置") : t("开始一个新的研究项目")}</h2><p>{t("文献、PDF、笔记和 PI 动态都保存在这个项目的资料夹中。")}</p></div><button type="button" className="icon-button" aria-label={t("关闭项目对话框")} disabled={busy} onClick={onClose}><X size={20} /></button></div><div className="project-form">
    {field('name', t("项目名称"), t("例如：海马与空间导航"))}{field('question', t("你想回答的研究问题"), t("描述研究对象、环路、行为和你最关心的机制…"), true)}{field('keywords', t("检索关键词（中英文均可，用逗号分开）"), 'hippocampus, spatial navigation, place cells', true)}{field('species', t("物种或研究范围"), t("例如：小鼠为主，兼顾灵长类"))}{field('exclusions', t("暂时排除的方向（选填）"), t("帮助减少不相关结果"), true)}
    <label className="project-checkbox"><input type="checkbox" checked={form.weeklyEnabled} onChange={e => setForm({ ...form, weeklyEnabled: e.target.checked })} />{t("加入每周一的论文与已关注 PI 更新")}</label><p className="project-muted">{t("调研使用已连接的 Codex 会员；结果先进入候选区，由你决定是否加入文库。定时更新需要电脑与 Codex 保持运行。")}</p>{error && <p className="form-error" role="alert">{te(error)}</p>}</div><div className="modal-footer"><button className="button" type="button" disabled={busy} onClick={onClose}>{t("取消")}</button><button className="button primary" data-shortcut-save disabled={busy}>{busy ? <LoaderCircle className="spin" size={16} /> : <Check size={16} />}{project ? t("保存项目设置") : t("创建项目资料夹")}</button></div></form></dialog>;
}

function ResearchStatus({ job, stop, navigate, notify }) {
  const busy = ['running', 'stopping'].includes(job.status), [now, setNow] = useState(Date.now());
  useEffect(() => { if (!busy) return; setNow(Date.now()); const timer = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer); }, [busy, job.id]);
  const duration = ms => { const seconds = Math.max(0, Math.floor(ms / 1000)); return tx`${Math.floor(seconds / 60)} 分 ${String(seconds % 60).padStart(2, '0')} 秒`; };
  const elapsed = (busy ? now : Date.parse(job.finishedAt || job.startedAt)) - Date.parse(job.startedAt);
  const silent = now - Date.parse(job.lastActivityAt || job.startedAt);
  const phase = ({ connecting: t("连接会员"), preparing: t("准备请求"), waiting: t("等待模型"), thinking: t("分析资料"), searching: t("检索来源"), reading: t("核对网页"), writing: t("整理结果"), saving: t("保存结果"), downloading: t("下载全文"), stopping: t("正在停止") })[job.phase] || t("处理中");
  const task = (({ people: t("PI 与实验室调研"), initial: t("项目论文初筛"), weekly: t("近期进展筛选"), pdf: t("补充 PDF 全文"), dossier: t("PI 详细档案"), bibliography: t("PI 论文数据") })[job.kind] || t("调研任务")) + (job.piName ? ` · ${job.piName}` : '');
  return <section className={`project-run ${busy ? 'project-run-active' : ''}`} aria-label={t("调研任务状态")} data-phase={job.phase} data-status={job.status}>
    <div className="project-section-title"><h2>{task}{busy ? t(" · 进行中") : ''}</h2>{busy && <button className="button" disabled={job.status === 'stopping' || job.phase === 'saving'} onClick={stop}>{job.status === 'stopping' ? t("正在停止…") : job.phase === 'saving' ? t("正在保存…") : t("停止任务")}</button>}</div>
    <div className={`job-status ${job.status}`} role="status">{busy && <LoaderCircle className="spin" size={16} />}{busy ? phase : ({ completed: t("已完成"), failed: t("未完成"), interrupted: t("已中断") })[job.status]}</div>
    <p className="job-message">{te(job.message)}</p>{busy && job.detail && <p className="job-source">{t("当前来源：")}{job.detail}</p>}
    <div className="job-metrics"><span className="job-elapsed">{busy ? t("已用时") : t("耗时")} {duration(elapsed || 0)}</span>{!['pdf', 'bibliography'].includes(job.kind) && job.effort && <span>GPT-6 · {effortLabel(job.effort)}</span>}<span>{job.searches || 0}{t(" 次来源检索／核验")}</span></div>
    {busy && <><p className="job-background-hint">{t("任务在后台进行，你可以继续阅读文献、记笔记或查看 PI。完成后即可开始下一项调研。")}</p>{silent >= 60000 && job.status === 'running' && job.phase !== 'saving' && <p className="job-wait-hint">{duration(silent)}{t("未收到新进度，可能在等待模型或网络。可以继续等待，或停止后重试。")}</p>}</>}
    {!busy && job.profiles != null && <button className="text-button" onClick={() => navigate('people')}>{t("查看 PI 与实验室 ")}<ArrowRight size={14} /></button>}
    {!busy && job.candidates != null && job.kind !== 'people' && <button className="text-button" onClick={() => navigate('weekly')}>{t("查看候选论文 ")}<ArrowRight size={14} /></button>}
    {job.results && <details><summary>{t("查看 PDF 下载结果（")}{job.results.length}{t(" 篇）")}</summary><div className="download-results">{job.results.map(r => <div key={r.id}><strong>{r.status === 'downloaded' ? t("已关联") : t("需手动导入")} · {r.title}</strong><p>{r.reason || tx`${r.pages} 页 · 标题已核验`}</p>{r.url && <button className="text-button" onClick={() => api.openExternal(r.url).catch(e => notify(e.message))}>{t("打开来源 ")}<ExternalLink size={13} /></button>}</div>)}</div></details>}
  </section>;
}

export function ProjectHub({ project, library, job, start, stop, navigate, edit, schedule, notify }) {
  const missing = library.papers.filter(p => !p.pdf), pending = (library.weekly?.candidates || []).filter(c => c.status === 'pending').length;
  const people = library.people?.profiles || [], busy = ['running', 'stopping'].includes(job?.status);
  const stages = [
    { step: '01', kind: 'initial', title: t("筛选项目论文"), icon: Search, description: t("从研究问题出发，查找奠基工作、机制证据、关键方法和最新进展。"), action: t("开始全网初筛"), run: () => start('initial'), footer: tx`${pending} 篇待你审核`, link: () => navigate('weekly') },
    { step: '02', kind: 'people', title: t("认识 PI 与实验室"), icon: Users, description: t("从核心作者延伸到相关实验室，记录研究方向、资助、大项目与团队动态。"), action: t("调研 PI 与实验室"), run: () => start('people'), footer: tx`${people.length} 位 PI · ${people.filter(p => p.followed).length} 位已关注`, link: () => navigate('people') },
    { step: '03', kind: 'pdf', title: t("建立文库与全文"), icon: Download, description: t("候选论文经你收录后，查找可下载的全文，核验标题并关联到文库。"), action: t("下载缺失 PDF"), run: () => start('pdf'), disabled: !missing.length, footer: tx`${library.papers.length} 篇已入库 · ${missing.length} 篇待补全文`, link: () => navigate('library') },
    { step: '04', kind: 'weekly', title: t("持续跟进研究"), icon: CalendarDays, description: t("每周一筛选新论文，并查看已关注 PI 的公开变化。推荐结果保留在候选区。"), action: t("现在筛选近期进展"), run: () => start('weekly'), footer: project.weeklyEnabled ? (schedule?.label || t("已加入项目更新 · 待配置定时任务")) : t("这个项目已暂停周一更新"), link: () => navigate('weekly') },
  ];
  return <div className="project-scroll"><div className="project-page"><div className="page-eyebrow">RESEARCH PROJECT</div><div className="project-heading"><div><h1>{project.name}</h1><p>{project.question}</p></div><div><button className="button" onClick={() => api.openProject().catch(e => notify(e.message))}><FolderOpen size={16} />{t("打开项目文件夹")}</button><button className="icon-button" aria-label={t("编辑项目设置")} onClick={edit}><Settings2 size={19} /></button></div></div><div className="project-keywords">{project.keywords.map(k => <span key={k}>{k}</span>)}</div>
    <button className="project-experiments" onClick={() => navigate('experiments')}><GitBranch size={24} /><div><strong>{t("我的实验进程")}</strong><p>{t("用思维导图串起实验步骤，记录结果与图片证据。")}</p></div><span>{(library.experiments?.nodes || []).filter(n => !n.archived && n.status === 'done').length} / {(library.experiments?.nodes || []).filter(n => !n.archived).length}{t(" 步骤已完成")}</span><ArrowRight size={17} /></button>
    {busy && <ResearchStatus job={job} stop={stop} navigate={navigate} notify={notify} />}
    <div className="workflow-heading"><h2>{t("从问题到积累，让每一步连起来")}</h2><span>{t("每个项目都有同一套工作流程")}</span></div><div className="workflow-grid">{stages.map(stage => <article className={`workflow-card ${busy && job.kind === stage.kind ? 'workflow-running' : ''}`} key={stage.step}><div className="workflow-top"><stage.icon size={23} /><span>{stage.step}</span></div><h3>{stage.title}</h3><p>{stage.description}</p><button className="button" disabled={busy || stage.disabled} onClick={stage.run}>{busy && job.kind === stage.kind ? <><LoaderCircle className="spin" size={14} />{job.status === 'stopping' ? t("正在停止…") : t("正在后台运行…")}</> : <>{stage.action}<ArrowRight size={14} /></>}</button><button className="workflow-link" onClick={stage.link}>{stage.footer}<ArrowRight size={13} /></button></article>)}</div>
    {!busy && (job ? <ResearchStatus job={job} stop={stop} navigate={navigate} notify={notify} /> : <section className="project-run"><p className="project-muted">{t("从上面的任意一步开始。检索范围和结果会保存在这个项目的调研记录中。")}</p></section>)}
    <div className="project-directory"><FolderOpen size={19} /><div><strong>{t("所有积累，都有自己的位置")}</strong><p>{t("文献与 PDF · 论文候选 · PI 资料 · 实验记录与图片 · 调研记录 · 下载清单 · 原始材料")}</p><code>{project.directory}</code></div></div>
  </div></div>;
}

const eventLabels = { get funding() { return t("Funding"); }, get project() { return t("大项目"); }, get team() { return t("团队变化"); }, get hiring() { return t("招聘"); }, get publication() { return t("重要论文"); } };
export function PeopleView({ project, people = { profiles: [], events: [], batches: [] }, update, start, busy, query, notify, startPi, job, stop, refresh }) {
  const [selectedId, setSelectedId] = useState(null);
  const [tab, setTab] = useState('labs'), [onlyFollowed, setOnlyFollowed] = useState(false), [type, setType] = useState('all'), [pending, setPending] = useState('');
  const followed = people.profiles.filter(p => p.followed), term = query.trim().toLowerCase();
  const profiles = people.profiles.filter(p => (!onlyFollowed || p.followed) && [p.name, p.institution, p.focus, p.relevance].join(' ').toLowerCase().includes(term));
  const ids = new Set(profiles.map(p => p.id));
  const events = people.events.filter(e => ids.has(e.piId) && (type === 'all' || e.type === type)).sort((a, b) => (b.eventDate || b.detectedOn).localeCompare(a.eventDate || a.detectedOn));
  const sourceLinks = sources => <div className="pi-sources">{sources.map(s => <button className="text-button" key={s.url} onClick={() => api.openExternal(s.url).catch(e => notify(e.message))}>{s.label}<ExternalLink size={12} /></button>)}</div>;
  const selected = people.profiles.find(p => p.id === selectedId);
  if (selected) return <PiDetail key={selected.id} person={selected} people={people} project={project} back={() => setSelectedId(null)} update={update} start={startPi} busy={busy} notify={notify} refresh={refresh} statusPanel={job?.piId === selected.id ? <ResearchStatus job={job} stop={stop} navigate={() => setSelectedId(null)} notify={notify} /> : busy ? <p className="dossier-note">{t("另一个调研正在后台运行，结束后可更新这份档案。")}</p> : null} />;
  return <div className="project-scroll"><div className="project-page people-page"><div className="page-eyebrow">PEOPLE & LABS · {project.name}</div><div className="project-heading"><div><h1>{t("PI 与实验室")}</h1><p>{t("跟进与你的研究有关的人、方向和资源。")}</p></div><button className="button primary" disabled={busy} onClick={() => start('people')}><Search size={16} />{t("调研与补充名单")}</button></div><div className="people-overview"><span><b>{people.profiles.length}</b>{t(" 位 PI")}</span><span><b>{followed.length}</b>{t(" 位已关注")}</span><span><b>{people.events.length}</b>{t(" 条有来源的记录")}</span><p>{t("关注后加入周一动态检索。历史背景与新进展分别标明。")}</p></div><div className="people-controls"><div className="library-tabs">{[['labs', t("实验室档案")], ['events', t("动态时间线")]].map(([id, label]) => <button key={id} className={tab === id ? 'active' : ''} onClick={() => setTab(id)}>{label}</button>)}</div><label><input type="checkbox" checked={onlyFollowed} onChange={e => setOnlyFollowed(e.target.checked)} />{t("只看已关注")}</label>{tab === 'events' && <select aria-label={t("PI 动态类型")} value={type} onChange={e => setType(e.target.value)}><option value="all">{t("所有动态")}</option>{Object.entries(eventLabels).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select>}</div>
    {tab === 'labs' ? <div className="pi-grid">{profiles.map(p => <article className="pi-card" key={p.id}><div className="pi-card-top"><div className="pi-avatar">{p.name.split(/\s/).filter(Boolean).slice(0, 2).map(s => s[0]).join('')}</div><div><h2><button className="pi-name-button" onClick={() => setSelectedId(p.id)}>{p.name}</button></h2><p>{p.institution}</p></div><button className={`button ${p.followed ? 'pi-followed' : ''}`} disabled={pending === p.id} onClick={async () => { setPending(p.id); try { await update(p.id, { followed: !p.followed }); } catch (e) { notify(e.message); } finally { setPending(''); } }}>{p.followed ? <Check size={13} /> : <Plus size={13} />}{p.followed ? t("已关注") : t("关注")}</button></div><p>{p.focus}</p><div className="pi-relevance"><span>{t("与本项目的关系")}</span><p>{p.relevance}</p></div>{sourceLinks(p.sources)}<div className="pi-card-footer"><div className="pi-checked">{t("资料核对：")}{p.checkedOn}</div><button className="text-button pi-detail-link" onClick={() => setSelectedId(p.id)}>{t("详细档案 ")}<ArrowRight size={12} /></button></div></article>)}</div> : <div className="pi-timeline">{events.map(e => <article className="pi-event" key={e.id}><div className="pi-event-date"><b>{e.eventDate || t("日期未披露")}</b><span>{e.baseline ? t("历史／基线记录") : t("公开动态")}</span></div><div className="pi-event-body"><div className="pi-event-meta"><span>{eventLabels[e.type]}</span><b>{people.profiles.find(p => p.id === e.piId)?.name}</b>{e.journal && <span>{e.journal}</span>}</div><h2>{e.title}</h2><p>{e.summary}</p><div className="pi-relevance"><span>{t("项目关联 · 分析")}</span><p>{e.relevance}</p></div><p className="pi-caveat">{e.caveat}</p>{sourceLinks(e.sources)}<div className="pi-checked">{t("发现／核对：")}{e.detectedOn}</div></div></article>)}</div>}
    {!(tab === 'labs' ? profiles : events).length && <div className="empty-state"><Users size={32} /><h3>{tab === 'labs' ? t("为这个项目建立 PI 名单") : t("暂时没有符合筛选的动态")}</h3><p>{tab === 'labs' ? t("先调研相关实验室，再选择你想持续关注的 PI。") : t("周一任务会核查已关注 PI 的资助、项目、团队和论文来源。")}</p></div>}
    <p className="project-muted">{t("Funding 和团队资料只记录公开来源。来源没有说明的金额、角色和发生日期会明确保留为未知。")}</p>
  </div></div>;
}
